language: julia
os:
    - linux
julia:
    - 1.0
    - 1.1

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
      - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - julia --project=docs/ -e 'Pkg.add("Plots"); Pkg.add("GR"); using Plots'
      - julia --project=docs/ docs/make.jl
      after_success: skip
